### ISSUE TITLE
Performance Monitoring

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/MongoDB#18]
https://docs.mongodb.com/manual/administration/production-notes/#recommended-configuration

- `iostat -xmt 1`

**Comment by xpdavid** [comment]
How https://github.com/percona/mongodb_exporter and https://prometheus.io/ works together. Give proper configurations here.

**Comment by langyanbin0314** [comment]
For CentOS
1. Install the repository package:
`sudo yum install http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm`

2. Install the required Percona Server for MongoDB package
`$ sudo yum install Percona-Server-MongoDB-34`

Percona Server for MongoDB stores data files in `/var/lib/mongodb/` by default. The configuration file is `/etc/mongod.conf`.

3. Start the service
`$ sudo service mongod start`

4. Check service status
`$ sudo service mongod status`

5. Stop the service
`$ sudo service mongod stop`

**Comment by xpdavid** [comment]
@langyanbin0314 Thank you for your input. However, there is not sudo permission on the node. Is there another way to do it?

**Comment by langyanbin0314** [comment]
mongodb_exporter:
1. Download at `https://github.com/percona/mongodb_exporter/releases`
2. Extract 
    `tar xvfz mongodb_exporter-*.tar.gz`
    `cd mongodb_exporter-*`
3. Build `./mongodb_exporter make`
4. `export MONGODB_URL='mongodb://localhost:27017'`
   `./mongodb_exporter <flags>`

**Comment by langyanbin0314** [comment]
https://www.slideshare.net/TimVaillancourt/monitoringwithprometheusgrafanatutorial
