### ISSUE TITLE
Explore the two/three different storage engines

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/MongoDB#25]
It seems WiredTiger Storage Engine comes into picture in recent release.
MMAPv1 Storage Engine is the old one.

I remember the lecture note mention that mongodb also use Log-structured merge-tree. Is that tree?
What're the differences between MMAPv1 Storage Engine, WiredTiger Storage Engine and In-Memory Storage Engine

https://docs.mongodb.com/manual/storage/

**Comment by elijahsk** [comment]
**WiredTiger vs MMAPV1**

WiredTiger uses document-level concurrency control for write operations. As a result, multiple clients can modify different documents of a collection at the same time.
MMAPV1 uses collection-level concurrency control, making updates less efficient.

WiredTiger supports compression of all collections and indexes, minimizing storage at the expenses of CPU.
MMAPV1 does not support compression.
However, it is debatable if the small data volume worth the additional CPU time needed.

**WiredTiger vs In-Memory**

By avoiding disk I/O, the in-memory storage engine allows for more predictable latency of database operations.
However, all data must be able to fit into the specified memory size.
The in-memory storage engine is non-persistent and only writes a small amount of data e.g. diagnostic data.

In addition to running as standalones, mongod instances that use in-memory storage engine can run as part of a replica set or part of a sharded cluster.

**WiredTiger BTree vs Wired Tiger LSM Tree**

Comparing the LSM Write Throughput to the Btree Write Throughput. Notice that both are able to sustain the 30,000 inserts a second requested by the rate limited workload. The LSM setup manages to sustain between 1.5x and 2x the insert throughput of btree. This is expected - LSM is optimized for write heavy workloads.

The read throughput using a btree is between 1.5x and 3x that achieved using an LSM tree. The difference becomes more pronounced as more read threads are added.

If you don't require extreme write throughput btree is likely to be a better choice. Read throughput is better and high volumes of writes can be maintained. If you have a workload that requires a high write throughput LSM is the best choice.

Full article at: [https://github.com/wiredtiger/wiredtiger/wiki/Btree-vs-LSM](https://github.com/wiredtiger/wiredtiger/wiki/Btree-vs-LSM)

**Possible Engine Choices**

1. All WiredTiger BTree;
2. WiredTiger LSM Tree on severely write-intensive table and BTree on the rest;
3. In-Memory with a hidden WiredTiger replica to persists storage.

**Comment by xpdavid** [comment]
https://jira.mongodb.org/browse/SERVER-18396

**Comment by langyanbin0314** [comment]
1. The difference between a B and B+ tree is that, in a B-tree, the keys and data can be stored in both the internal and leaf nodes, whereas in a B+ tree, the data and keys can only be stored in the leaf nodes.

2. The leaf nodes of the tree store pointers to records rather than actual records.

3. Advantage of using B tree
    - keeps keys in sorted order for sequential traversing
    - uses a hierarchical index to minimize the number of disk reads
    - uses partially full blocks to speed insertions and deletions
    - keeps the index balanced with a recursive algorithm

**Comment by xpdavid** [comment]
@langyanbin0314 Does B tree good at random write?
