### ISSUE TITLE
Resonse behind dramatic difference between majority and one

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/MongoDB#35]
The majority's throughput is around 0.7 while the one's throughput is around 0.17, try to find out why. Both under NC10

**Comment by langyanbin0314** [comment]
For a given secondary node, replication lag is the delay between the time an operation occurs on the primary and the time that same operation gets applied on the secondary.

Majority ensures that each write to the cluster is replicated to more than one node before the command returns which leads to higher replication lag than One which only requires an acknowledgement from the primary.

On the other hand, Majority makes sure that the write operation is truly committed

**Comment by xpdavid** [comment]
Should be related to this https://docs.mongodb.com/manual/reference/write-concern/#wc-ack-behavior
