### ISSUE TITLE
Give calculation to say that orderItem table won't exceed the maximum document size

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/MongoDB#8]

**Comment by leshweyeewin** [comment]
Initial Data:
16 warehouses
10 districts per warehouse
3000 orders per district

Transaction Data:
40 xact files 
20 new order xact per xact file
Assuming all transactions create new order for same district, 
Max_O_ID = 3000 + 40×20 = 3800

Transaction Workload Assumption:
Number of items per new order: [5, 20]

ORDERITEM Document size ~ 1664 bytes

ORDERITEM : { (30+34+1600=1664)+(1 bit)
    _ID: "O_W_ID. + "_" + "O_D_ID" + "_" + O_ID S (2+2+2+4)
   
    O_CARRIER_ID : int (4)
    O_C_ID : int (4)
    O_OL_CNT : int (4)
    O_ALL_LOCAL : bool (1 bit)
    O_ENTRY_D : date (8)
   
    CUSTOMER : { (34)
        C_FIRST : string (16)
        C_MIDDLE : string (2)
        C_LAST : string (16)
    }
 
    ORDERLINES : [ (80×20) = 1600
       {
          OL_NUMBER : int (4)
          OL_DELIVERY_D : date (8)
          OL_AMOUNT : double (8)
          OL_SUPPLY_W_ID : int (4)
          OL_QUANTITY :  int (4)
          OL_DIST_INFO : string (24)
          OL_I_ID :  int (4)
          
          I_NAME : string (24)
       },
       ...
    ]
}
